### ISSUE TITLE
Adding comments to the work item view [enhancement]

### ISSUE THREAD

**Issue by anshuman852** [PurpleSoftSrl/azure_devops_app#1]
Hi, thanks for working on a very clean app for azure devops. 
I wanted to request this feature 
here is the api doc https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/comments/get-comments?view=azure-devops-rest-7.0&tabs=HTTP#get-the-first-page-of-comments

Being able to see comments would be very helpful.

**Comment by sstasi95** [comment]
Hi, good suggestion!

We're already working on this feature, but using [this api](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/updates/list?view=azure-devops-rest-7.0&tabs=HTTP). In this way, you'll be able to see not only the comments but also the history of updates to the work item (i.e. state, type, effort and assignee changes).

It will be released in the next days.

**Comment by anshuman852** [comment]
Hi Thanks a lot, it works great
