### ISSUE TITLE
Would be nice to get pipeline name in pipelines list

### ISSUE THREAD

**Issue by jviolante-dr** [PurpleSoftSrl/azure_devops_app#23]
As for now we use mono repo strategy with one pipeline for each artefact in the repo. We only have one project obviously. 
Would be great to be able to filter by pipeline to get same benefits as current project filter for multi-repo/project approach

**Comment by sstasi95** [comment]
Understood, I'll look into it.

**Comment by lonewolf311icloud** [comment]
Purple soft azure
Lmao 😆
