### ISSUE TITLE
Feature request: Work Item links

### ISSUE THREAD

**Issue by Eonasdan** [PurpleSoftSrl/azure_devops_app#39]
Hello thanks for creating this app. It's amazing that MS didn't provide a good solution for it 

Could you add a way to navigate to a linked work item? For instance, from a PBI to the parent feature and from the feature a list of PBIs.

**Comment by JamborJan** [comment]
I am reading this feature request as a way to read links and navigate through work item links.

From my point of view it would also be good to be able to add links to work items.

I am mainly using the app on the go or on the couch to dump my thoughts into work items and groom the backlog. Adding links would be a requirement too in that case.

**Comment by sstasi95** [comment]
Links are now visible in the work item history (will be released shortly). @JamborJan I've opened a new issue to track links creation (#47).
