### ISSUE TITLE
Area path and iteration path support

### ISSUE THREAD

**Issue by carun** [PurpleSoftSrl/azure_devops_app#4]
Thanks for creating this simple but easy to use app for ADO.

Can you please add support for area path and iteration path in work items view?

**Comment by sstasi95** [comment]
Hi, sorry for the late response.

Would you like to be able to filter work items by area path and iteration path (like you can do by project/type/status/assignee)? Or do you want to view (and edit) area path and iteration path in the work item detail page? Or both?

**Comment by carun** [comment]
Both please.
