### ISSUE TITLE
Pipelines and Work Items Unauthorized

### ISSUE THREAD

**Issue by Zachdehooge** [PurpleSoftSrl/azure_devops_app#49]
Work items and pipelines are showing unauthorized. Commits, PR’s, and repo code are able to be seen. Could be an issue on my end but wasn’t sure what to do from here. Living the app so far

**Comment by sstasi95** [comment]
Hi, did you sign in with PAT or with Microsoft sign in? If you signed in with PAT, you need to add read permission to Work Items and Build (see the attached screenshot), if you signed in with Microsoft you should ask your organization admin to give you these permissions.


<img width="601" alt="Screenshot 2024-11-22 at 11 40 55" src="https://github.com/user-attachments/assets/1fe74a48-b833-451e-8196-e02a83c5313e">

**Comment by Zachdehooge** [comment]
That worked! Thank you so much!
