### ISSUE TITLE
Clicking Settings (iOS) gives UnAuthorized Error 

### ISSUE THREAD

**Issue by akselsoft** [PurpleSoftSrl/azure_devops_app#5]
Steps:
1. Logged into my Project via PAT. Everything looks great.
2. Click on Settings (Wrench)

Observed: Error Unauthorized. Tap to Retry

Expected: Unsure. What should I be able to do?

![IMG_F082E76173B8-1](https://github.com/PurpleSoftSrl/azure_devops_app/assets/642423/60035568-1f8c-4a8e-a4c9-7e47879441ce)

**Comment by sstasi95** [comment]
When you navigate to the settings page, an api request is made to get the list of your organizations (to allow the user to switch between them). If you get unauthorized, probably your PAT doesn't have 'All organizations' option enabled. If this is the case, you can try to create a new PAT with that option enabled.

Anyway, we should allow the user to view the page even if he gets a 401.

[This is the api documentation](https://learn.microsoft.com/en-us/rest/api/azure/devops/account/accounts/list?view=azure-devops-rest-7.0&tabs=HTTP#by-member), and [this is the code](https://github.com/PurpleSoftSrl/azure_devops_app/blob/030a8a9c8d1665c9712229dd65c716bc48c8098b/lib/src/services/azure_api_service.dart#L497)
