### ISSUE TITLE
PAT visible

### ISSUE THREAD

**Issue by pless84** [PurpleSoftSrl/azure_devops_app#7]
The PAT should not be visible and editable that is a security risk.

**Comment by sstasi95** [comment]
Hi, 
I agree that it should be hidden, but I think it may be useful to see it, for example to know which PAT you used to login. What do you think about making it visible/hidden with a toggle? Like it's usually done with password form fields. Or would you just hide it completely?

**Comment by pless84** [comment]
When you first make it on Azure it is only showed once, maybe it should not be editable and the name you give it should be showed only. If you forget it then you have to make a new one.
