### ISSUE TITLE
Store latest entry for workitems

### ISSUE THREAD

**Issue by woehrl01** [PurpleSoftSrl/azure_devops_app#8]
It would be great if the last selected project, area path and Iteration would be persistent across new work items.

An alternative would be possibility to store default values (e.g `@CurrentItereration` of a specific team)

**Comment by sstasi95** [comment]
Hi, do you mean that if you have a selected project/area/iteration and you press the '+' icon to add a new work item, you would like to have the project/area/iteration values already set?

**Comment by woehrl01** [comment]
Exactly! 👍🏻
